### ISSUE TITLE
Remove need for loadbalancer

### ISSUE THREAD

**Issue by DaemonBeast** [SkeldJS/Hindenburg#1]
![image](https://user-images.githubusercontent.com/57999551/120036659-64457400-bff8-11eb-8b8c-d48fcdb8820f.png)

**Comment by edqx** [comment]
This was more difficult than I thought it would be.

**Comment by edqx** [comment]
Anyone who wants to do this should have a look at the https://github.com/SkeldJS/hbplugin-noloadbalancer plugin that I've been making.
