### ISSUE TITLE
RemovePlayerMessage in BaseRoom.handleStart causes an error

### ISSUE THREAD

**Issue by gabriel-nsiqueira** [SkeldJS/Hindenburg#27]
So I was starting the game and someone had a very high ping, so they missed the ready packet. The server, as normal, tried to send the RemovePlayerMessage but it causes an error. I tried starting without that person and it started.
<img width="1142" alt="Screen Shot 2021-09-30 at 18 14 03" src="https://user-images.githubusercontent.com/15304929/135531065-9a9393d2-cef0-49c5-80cd-33d655842242.png">

**Comment by edqx** [comment]
I think this is fixed
