### ISSUE TITLE
Api to get absolute path of a certain plugin

### ISSUE THREAD

**Issue by gabriel-nsiqueira** [SkeldJS/Hindenburg#28]
The plugin api needs a way to get the absolute path of a certain plugin so you can get assets and other files.

**Comment by edqx** [comment]
You can probably use the `.pluginDirectory` property on the plugin, and you can access the plugin by it's id from the worker's pluginLoader

**Comment by gabriel-nsiqueira** [comment]
I didn't notice it, thanks
