### ISSUE TITLE
Build Errors 2

### ISSUE THREAD

**Issue by MacaylaMarvelous81** [SkeldJS/Hindenburg#5]
Four more build errors 😞 
### Info
Same versions as previous
Commit: 2963aed6458be819f28ee579806a6da676a9c80b
```ts
src/util/format-player.ts:11:24 - error TS2339: Property 'info' does not exist on type 'PlayerData'.

|11| const colour = player.info ? player.info.color : Color.Grey;

src/util/format-player.ts:11:38 - error TS2339: Property 'info' does not exist on type 'PlayerData'.

|11| const colour = player.info ? player.info.color : Color.Grey;

src/util/format-player.ts:12:22 - error TS2339: Property 'info' does not exist on type 'PlayerData'.

|12| const name = player.info.name || "<No Name>" : "<No Data>";

src/util/format-player.ts:12:36 - error TS2339: Property 'info' does not exist on type 'PlayerData'.

|12| const name = player.info.name || "<No Name>" : "<No Data>";
```
I couldn't reopen the previous issue #4 :p

**Comment by edqx** [comment]
Answered in #4.

**Comment by edqx** [comment]
You deleted the comment so I'll post the solution here instead.
> Run `yarn install` again as `.info` only exists on the new version of SkeldJS that I bumped Hindenburg up to in https://github.com/SkeldJS/Hindenburg/commit/7b8e0d769a93565afec237fbf425241a33ae84ff.

**Comment by MacaylaMarvelous81** [comment]
Not a build error, but when starting the server with a config, it shows the crewmate ascii art like it has a config, but then says it couldn't find a config and overwrites the current config. The config before it was overwritten still takes place but since it is overwritten with the default config future server starts will use new config. It tells you to run it again to continue but still listens as a server. Without a config it doesn't show the ascii art, and creates the default config like normal.

**Comment by edqx** [comment]
Is it alright if this is opened as a new issue? Someone else was having this issue the other day and I couldn't find out why. I could do with a screenshot of the terminal ideally.

**Comment by MacaylaMarvelous81** [comment]
Sure

**Comment by MacaylaMarvelous81** [comment]
Opened #6
