### ISSUE TITLE
Error while installing dependencies

### ISSUE THREAD

**Issue by Pietrodjaowjao** [SkeldJS/Hindenburg#57]
when i use the yarn command, this happens
![Captura de tela de 2021-12-06 21-13-46](https://user-images.githubusercontent.com/77608535/144942820-b2958a4e-c964-4d91-b30a-90d10bea78dd.png)
:
i installed NodeJS, npm, git and yarn

**Comment by edqx** [comment]
What version of node are you on? Try updating to version 16 if you are not already.
