### ISSUE TITLE
Configuration Overwriting

### ISSUE THREAD

**Issue by MacaylaMarvelous81** [SkeldJS/Hindenburg#6]
### Description
When starting the server with a config, it shows the crewmate ascii art like it has a config, but then says it couldn't find a config and overwrites the current config. The config before it was overwritten still takes place but since it is overwritten with the default config future server starts will use new config. It also overwrites the default config. It tells you to run it again to continue but still listens as a server. Without a config it doesn't show the ascii art, and creates the default config like normal.
### Info
Node version 14.3.0
Yarn version 1.22.4
Commit 2963aed6458be819f28ee579806a6da676a9c80b
### Reproduction Steps
1. Setup server
2. Edit server config (or don't)
3. Run `yarn start:load-balancer`
4. Config is overwritten, server still listening
### Media/Screenshot/Video
NOTE: .txt is on purpose to allow upload to GitHub
Before run (edited): 
[config.json.txt](https://github.com/SkeldJS/Hindenburg/files/6586178/config.json.txt)
After run (default): [config.json.txt](https://github.com/SkeldJS/Hindenburg/files/6586188/config.json.txt)
Terminal screenshot: https://i.imgur.com/4UMb1n4.png

**Comment by edqx** [comment]
Should be fixed in https://github.com/SkeldJS/Hindenburg/commit/bc471aa924b3fe8035d7e186fea747daa8147a49.

Also I wonder if the IP that you posted in your screenshot was intentional? Else I suggest you remove that from imgur if possible.

**Comment by MacaylaMarvelous81** [comment]
Whoops thanks for the headsup

**Comment by edqx** [comment]
Okay, actually you know what - sorry about this, you should probably go ahead and git pull again. I made a mistake in https://github.com/SkeldJS/Hindenburg/commit/cfe9f5f04c74d1c3f8baeed9b5b5a22f9c8675b8 and assumed that plugins would be built in their respective folders in the plugins directory.

I'm currently not sure how I want to do it so I'm just going to go with building plugins as if they were part of the project itself for now, so I reverted the changes from the commit above and updated tsconfig to include the plugins directory. Be sure to build after you pull.
