### ISSUE TITLE
API for roles

### ISSUE THREAD

**Issue by gabriel-nsiqueira** [SkeldJS/Hindenburg#80]
SkeldJS has a [room.registerRole(RoleClass)](https://skeldjs.github.io/Hindenburg/classes/Room.html#registerRole)

It would be nice if Hindenburg had a `@Role` like the rest of the Hindenburg api.

**Comment by edqx** [comment]
Added in c0ca76b800a39f64d1be446a7cfb268821d54e41...1c37016de0ccea89560ca7776b7a1255d6e02633
