### ISSUE TITLE
When the game name contains Chinese characters, the player cannot join the room correctly

### ISSUE THREAD

**Issue by LikeJson** [SkeldJS/Hindenburg#84]
Phenomenon 1
When the host's username contains Chinese, the username cannot be displayed correctly.
and other players cannot join the room
![image](https://user-images.githubusercontent.com/85022954/172826071-0e9dab94-c483-4a4e-a260-de084b268278.png)
Phenomenon 2
When another player's username contains Chinese, it will not be able to join other rooms, but the log shows that it has joined

![image](https://user-images.githubusercontent.com/85022954/172827321-79092f5c-c43b-42f9-a318-1c507cd1268c.png)

**Comment by edqx** [comment]
Uh oh. Does this actually work fine on vanilla/official servers?

**Comment by zrotl** [comment]
Hi, I'm japanese and when the player use japanese characters, I have same problems.
It work fine on official servers and Impostor servers, so they're Hindenburg's problems.

**Comment by LikeJson** [comment]
Yes, It work fine on official servers 
sorry to reply too late

**Comment by edqx** [comment]
Thanks, I'll have a look at this at some point today.

**Comment by edqx** [comment]
![image](https://user-images.githubusercontent.com/60631511/175108335-150faadf-45c3-48f2-86cb-0f031a40e644.png)
