### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by j0nas500** [SkeldJS/Hindenburg#90]
Tried to join the Hindenburg server today with friends, some were on it with android tablets/smartphones. They got into the lobby, at the start of the game, the game behaved strangely and nothing happened anymore.

**Comment by edqx** [comment]
What do you mean the game behaved strangely? In what way?

I haven't tried it on mobile but it shouldn't (?) be any different.

**Comment by j0nas500** [comment]
Sometimes everyone was in an endless loading screen. Then there was just a freeze frame when starting the Lobbie and sometimes one or the other made it back into the lobby. That's what I mean by weird behavior :D

Unfortunately no one could play on mobile today :(

**Comment by edqx** [comment]
Ah, sorry about that. Keep updated for fixes :)

Did you have any issues on desktop?

**Comment by j0nas500** [comment]
So far only the reported: #91 #92 #93

**Comment by edqx** [comment]
Closing due to inactionable.

Not sure what to make of this, sorry. I don't think mobile Among Us behaves any differently from desktop Among Us.

Feel free to open the issue if you have any more information on it though!
