### ISSUE TITLE
Start game button disappeared

### ISSUE THREAD

**Issue by j0nas500** [SkeldJS/Hindenburg#92]
While playing several rounds, I was suddenly removed the ability to start the game. I no longer had a start button and could not make any settings. But also no one else was given the possibility. So nobody could start a game from this lobby

**Comment by edqx** [comment]
Hi, I published a commit that tried to fix this: a704aa452a0fb842df9fe7361af245cf90db9854. Do you think you could check this out/test this for me? I've been unable to reproduce it myself.

**Comment by j0nas500** [comment]
Is unfortunately also difficult for me to reproduce, because it has fortunately only occurred once so far. But it will not be the last time that we play on the server. So I'll report if the problem is there again

**Comment by j0nas500** [comment]
Played again today and it did not happen again. I will close the issue for now
